### ISSUE TITLE
todo for 10/2

### ISSUE THREAD

**Issue by dyurovsky** [benjamincmorris/reference-game#1]
Dan

- [ ] finish model results section
- [ ] describe modeling approximation in supplemental
- [ ] results computed for simulation to write during co-writing

Ben
- [ ] add model plot to model results
- [ ] corpus supplemental in
